import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CatalogForm } from "@/components/catalog-form";
import { PageShell } from "@/components/page-shell";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ArrowLeft, Archive, Trash2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
export const Route=createFileRoute("/_authenticated/billetterie/$id")({component:EditTicket,head:()=>({meta:[{title:"Billetterie — JEITINHO"}]})});
function EditTicket(){const {id}=Route.useParams();const navigate=useNavigate();const qc=useQueryClient();const {data,isLoading,error}=useQuery({queryKey:["ticket-offer",id],queryFn:async()=>{const {data,error}=await supabase.from("ticket_offers").select("*").eq("id",id).single();if(error)throw new Error(error.message);return data as any}});if(isLoading)return <PageShell title="Chargement…"><Card className="h-48 animate-pulse bg-muted/50"/></PageShell>;if(error||!data)return <PageShell title="Offre introuvable"><Card className="border-destructive/40 p-8">{error instanceof Error?error.message:"Impossible de charger cette offre."}</Card></PageShell>;const archive=async()=>{const {error}=await supabase.from("ticket_offers").update({is_published:false}).eq("id",id);if(error)return toast.error(error.message);toast.success("Offre archivée");await qc.invalidateQueries({queryKey:["ticket-offers"]});navigate({to:"/billetterie"})};const remove=async()=>{if(!confirm("Supprimer définitivement cette offre ?"))return;const {error}=await supabase.from("ticket_offers").delete().eq("id",id);if(error)return toast.error(error.message);toast.success("Offre supprimée");navigate({to:"/billetterie"})};return <PageShell eyebrow="Contenu / Catalogue" title={data.title} description="Modifier l'offre billetterie." actions={<div className="flex gap-2"><Link to="/billetterie"><Button variant="outline"><ArrowLeft className="mr-2 h-4 w-4"/>Billetterie</Button></Link><Button variant="outline" onClick={archive}><Archive className="mr-2 h-4 w-4"/>Archiver</Button><Button variant="ghost" className="text-destructive hover:text-destructive" onClick={remove}><Trash2 className="mr-2 h-4 w-4"/>Supprimer</Button></div>}><CatalogForm mode="ticket" initial={{...data,is_active:Boolean(data.is_published)}} onSubmit={async v=>{const {error}=await supabase.from("ticket_offers").update({title:v.title.trim(),venue:v.venue||null,event_date:v.event_date||null,public_price:v.public_price,supplier_net:v.supplier_net,commission_pct:v.commission_pct,currency:v.currency||"BRL",notes:v.notes||null,is_published:v.is_active,category:v.category||null,supplier_cost:v.supplier_cost,commission_basis:v.commission_basis||"sale_price"}).eq("id",id);if(error){toast.error(error.message);return;}toast.success("Offre enregistrée");await Promise.all([qc.invalidateQueries({queryKey:["ticket-offer",id]}),qc.invalidateQueries({queryKey:["ticket-offers"]})])}}/></PageShell>}
