import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CatalogForm } from "@/components/catalog-form";
import { TicketOfferVariantsEditor } from "@/components/ticket-offer-variants-editor";
import { PageShell } from "@/components/page-shell";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ArrowLeft, Archive, Trash2 } from "lucide-react";
import { fetchCatalogItem, updateCatalogItem, deleteCatalogItem } from "@/lib/catalog-gateway";
import { toast } from "sonner";
export const Route=createFileRoute("/_authenticated/billetterie/$id")({component:EditTicket,head:()=>({meta:[{title:"Billetterie — JEITINHO"}]})});
function EditTicket(){const {id}=Route.useParams();const navigate=useNavigate();const qc=useQueryClient();const {data,isLoading,error}=useQuery({queryKey:["ticket-offer",id],queryFn:()=>fetchCatalogItem<any>("ticket_offers",id)});if(isLoading)return <PageShell title="Chargement…"><Card className="h-48 animate-pulse bg-muted/50"/></PageShell>;if(error||!data)return <PageShell title="Offre introuvable"><Card className="border-destructive/40 p-8">{error instanceof Error?error.message:"Impossible de charger cette offre."}</Card></PageShell>;const archive=async()=>{try{await updateCatalogItem("ticket_offers",id,{is_published:false});toast.success("Offre archivée");await qc.invalidateQueries({queryKey:["ticket-offers"]});navigate({to:"/billetterie"})}catch(e){toast.error(e instanceof Error?e.message:"Archivage impossible.")}};const remove=async()=>{if(!confirm("Supprimer définitivement cette offre ?"))return;try{await deleteCatalogItem("ticket_offers",id);toast.success("Offre supprimée");navigate({to:"/billetterie"})}catch(e){toast.error(e instanceof Error?e.message:"Suppression impossible.")}};return <PageShell eyebrow="Contenu / Catalogue" title={data.title} description="Modifier l'offre billetterie." actions={<div className="flex gap-2"><Link to="/billetterie"><Button variant="outline"><ArrowLeft className="mr-2 h-4 w-4"/>Billetterie</Button></Link><Button variant="outline" onClick={archive}><Archive className="mr-2 h-4 w-4"/>Archiver</Button><Button variant="ghost" className="text-destructive hover:text-destructive" onClick={remove}><Trash2 className="mr-2 h-4 w-4"/>Supprimer</Button></div>}><div className="space-y-6"><CatalogForm mode="ticket" initial={{...data,is_active:Boolean(data.is_published)}} onSubmit={async v=>{try{await updateCatalogItem("ticket_offers",id,{title:v.title.trim(),venue:v.venue||null,event_date:v.event_date||null,public_price:v.public_price,supplier_net:v.supplier_net,commission_pct:v.commission_pct,currency:v.currency||"EUR",notes:v.notes||null,is_published:v.is_active,category:v.category||null,supplier_cost:v.supplier_cost,commission_basis:v.commission_basis||"sale_price",photo_url:v.photo_url||null,photo_ratio:v.photo_ratio||"16/9",title_en:v.title_en||null,title_es:v.title_es||null,title_pt:v.title_pt||null,description_en:v.description_en||null,description_es:v.description_es||null,description_pt:v.description_pt||null,venue_en:v.venue_en||null,venue_es:v.venue_es||null,venue_pt:v.venue_pt||null});toast.success("Offre enregistrée");await Promise.all([qc.invalidateQueries({queryKey:["ticket-offer",id]}),qc.invalidateQueries({queryKey:["ticket-offers"]})])}catch(e){toast.error(e instanceof Error?e.message:"Enregistrement impossible.")}}}/><TicketOfferVariantsEditor ticketOfferId={id}/></div></PageShell>}
