import { createFileRoute, Link, Outlet, useRouterState } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { fetchClients } from "@/lib/clients-gateway";
import { PageShell } from "@/components/page-shell";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { UserRound, Plus, RefreshCw } from "lucide-react";

export const Route = createFileRoute("/_authenticated/clients")({ component: Layout, head: () => ({ meta: [{ title: "Clients — JEITINHO" }] }) });
function Layout(){const path=useRouterState({select:r=>r.location.pathname});if(path.replace(/\/$/,"")!=="/clients")return <Outlet/>;return <ClientsList/>;}
function ClientsList(){const {data,isLoading,error,refetch,isFetching}=useQuery({queryKey:["clients"],queryFn:fetchClients});return <PageShell eyebrow="Base clients" title="Clients" description="Fiches, historique de voyages et documents. Chaque fiche est conservée dans le catalogue clients central du Hub." actions={<Link to="/clients/new"><Button className="btn-primary"><Plus className="mr-2 h-4 w-4"/>Nouveau client</Button></Link>}>
<div className="mb-5 flex justify-end"><Button variant="outline" size="sm" onClick={()=>refetch()} disabled={isFetching}><RefreshCw className="mr-2 h-4 w-4"/>Actualiser</Button></div>
{isLoading?<div className="text-sm text-muted-foreground">Chargement…</div>:error?<Card className="border-destructive/40 p-8"><h2 className="font-semibold">Impossible de charger les clients</h2><p className="mt-2 text-sm text-muted-foreground">{(error as Error).message}</p><Button className="mt-4" onClick={()=>refetch()}>Réessayer</Button></Card>:!data?.length?<Card className="border-dashed p-16 text-center"><UserRound className="mx-auto mb-4 h-8 w-8 text-primary"/><h2 className="text-xl" style={{fontFamily:"Fraunces, serif"}}>Aucun client pour l'instant</h2><p className="mt-2 text-sm text-muted-foreground">Créez une fiche manuellement ou convertissez un prospect qualifié depuis le CRM.</p><Link to="/clients/new" className="mt-6 inline-block"><Button className="btn-primary">Créer un client</Button></Link></Card>:<Card className="divide-y divide-border/60 border-border/60">{data.map(c=><Link key={c.id} to="/clients/$id" params={{id:c.id}} className="flex items-center justify-between gap-4 p-4 hover:bg-muted/30"><div className="min-w-0"><h3 className="truncate text-sm font-medium">{c.full_name}</h3><p className="mt-0.5 text-xs text-muted-foreground">{[c.email,c.phone].filter(Boolean).join(" · ")||"Pas de contact"}</p></div><span className="pill shrink-0">{c.stage??c.status??"—"}</span></Link>)}</Card>}</PageShell>;}
