import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CatalogForm } from "@/components/catalog-form";
import { PageShell } from "@/components/page-shell";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ArrowLeft, Archive, Trash2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
export const Route=createFileRoute("/_authenticated/services/$id")({component:EditService,head:()=>({meta:[{title:"Service — JEITINHO"}]})});
function EditService(){const {id}=Route.useParams();const navigate=useNavigate();const qc=useQueryClient();const {data,isLoading,error}=useQuery({queryKey:["service",id],queryFn:async()=>{const {data,error}=await supabase.from("services").select("*").eq("id",id).single();if(error)throw new Error(error.message);return data as any}});if(isLoading)return <PageShell title="Chargement…"><Card className="h-48 animate-pulse bg-muted/50"/></PageShell>;if(error||!data)return <PageShell title="Service introuvable"><Card className="border-destructive/40 p-8">{error instanceof Error?error.message:"Impossible de charger ce service."}</Card></PageShell>;const archive=async()=>{const {error}=await supabase.from("services").update({is_published:false}).eq("id",id);if(error)return toast.error(error.message);toast.success("Service archivé");await qc.invalidateQueries({queryKey:["services"]});navigate({to:"/services"})};const remove=async()=>{if(!confirm("Supprimer définitivement ce service ?"))return;const {error}=await supabase.from("services").delete().eq("id",id);if(error)return toast.error(error.message);toast.success("Service supprimé");navigate({to:"/services"})};return <PageShell eyebrow="Contenu / Catalogue" title={data.title} description="Modifier la fiche service." actions={<div className="flex gap-2"><Link to="/services"><Button variant="outline"><ArrowLeft className="mr-2 h-4 w-4"/>Services</Button></Link><Button variant="outline" onClick={archive}><Archive className="mr-2 h-4 w-4"/>Archiver</Button><Button variant="ghost" className="text-destructive hover:text-destructive" onClick={remove}><Trash2 className="mr-2 h-4 w-4"/>Supprimer</Button></div>}><CatalogForm mode="service" initial={{...data,is_active:Boolean(data.is_published)}} onSubmit={async v=>{const {error}=await supabase.from("services").update({title:v.title.trim(),description:v.description||null,group_slug:v.group_slug||null,category:v.category||null,price_label:v.price_label||null,price_from:v.price_from,currency:v.currency||"EUR",partner_id:v.partner_id||null,price_model:v.price_model||"fixed",supplier_net:v.supplier_net,supplier_cost:v.supplier_cost,fixed_cost:v.fixed_cost,commission_pct:v.commission_pct,commission_basis:v.commission_basis||"sale_price",is_published:v.is_active}).eq("id",id);if(error){toast.error(error.message);return;}toast.success("Service enregistré");await Promise.all([qc.invalidateQueries({queryKey:["service",id]}),qc.invalidateQueries({queryKey:["services"]})])}}/></PageShell>}
