import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { fetchCatalog } from "@/lib/catalog-gateway";
import { PageShell } from "@/components/page-shell";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Wrench, Search, RefreshCw, Package, Wallet, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";

export const Route = createFileRoute("/_authenticated/services")({ component: ServicesFactory, head: () => ({ meta: [{ title: "Services Factory — JEITINHO" }] }) });

function ServicesFactory() {
  const [search, setSearch] = useState("");
  const { data, isLoading, error, refetch, isFetching } = useQuery({ queryKey: ["services"], queryFn: () => fetchCatalog<any>("services", { order: "group_slug" }) });
  const rows = data ?? [];
  const visible = useMemo(() => { const q = search.trim().toLowerCase(); return rows.filter((s) => !q || [s.title, s.description, s.group_slug, s.category].filter(Boolean).join(" ").toLowerCase().includes(q)); }, [rows, search]);
  const groups = useMemo(() => [...new Set(visible.map((s) => s.group_slug).filter(Boolean))], [visible]);

  return <PageShell eyebrow="Catalogue commercial" title="Services Factory" description="Services de conciergerie distincts des expériences : assistance, logistique, confort et prestations à la carte.">
    <div className="mb-5 grid gap-3 sm:grid-cols-3"><Card className="p-4"><div className="flex items-center justify-between"><span className="text-xs text-muted-foreground">Services</span><Package className="h-4 w-4 text-primary" /></div><p className="mt-2 text-2xl font-semibold" style={{ fontFamily: "Fraunces, serif" }}>{rows.length}</p></Card><Card className="p-4"><div className="flex items-center justify-between"><span className="text-xs text-muted-foreground">Familles</span><Sparkles className="h-4 w-4 text-primary" /></div><p className="mt-2 text-2xl font-semibold" style={{ fontFamily: "Fraunces, serif" }}>{groups.length}</p></Card><Card className="p-4"><div className="flex items-center justify-between"><span className="text-xs text-muted-foreground">Usage</span><Wallet className="h-4 w-4 text-primary" /></div><p className="mt-2 text-sm font-medium">Devis · Voyage · Upsell</p></Card></div>
    <div className="mb-5 flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Rechercher un service…" value={search} onChange={(e) => setSearch(e.target.value)} /></div><Button variant="outline" onClick={() => refetch()} disabled={isFetching}><RefreshCw className={`mr-2 h-4 w-4 ${isFetching ? "animate-spin" : ""}`} />Actualiser</Button></div>
    {isLoading ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[0, 1, 2, 3].map((i) => <Card key={i} className="h-44 animate-pulse bg-muted/50" />)}</div> : error ? <Card className="border-destructive/40 p-8"><h3 className="font-semibold">Impossible de charger les services</h3><p className="mt-2 text-sm text-muted-foreground">{(error as Error).message}</p><Button className="mt-4" onClick={() => refetch()}>Réessayer</Button></Card> : !rows.length ? <Card className="border-dashed p-12 text-center"><Wrench className="mx-auto mb-4 h-8 w-8 text-primary" /><h3 className="text-xl" style={{ fontFamily: "Fraunces, serif" }}>Catalogue de services vide</h3><p className="mx-auto mt-2 max-w-xl text-sm text-muted-foreground">La table <strong>services</strong> ne retourne aucune ligne pour cet utilisateur. Si les services du site ont déjà été importés dans Supabase, il faut vérifier l'import ou les policies RLS plutôt que créer des données fictives.</p></Card> : !visible.length ? <Card className="border-dashed p-12 text-center"><Search className="mx-auto mb-4 h-7 w-7 text-primary" /><h3 className="text-xl" style={{ fontFamily: "Fraunces, serif" }}>Aucun résultat</h3><p className="mt-2 text-sm text-muted-foreground">Modifie la recherche.</p></Card> : <div className="space-y-6">{groups.length ? groups.map((group) => <section key={group}><div className="mb-3 flex items-center gap-2"><span className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">{group}</span><div className="h-px flex-1 bg-border" /></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.filter((s) => s.group_slug === group).map((service) => <ServiceCard key={service.id} service={service} />)}</div></section>) : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map((service) => <ServiceCard key={service.id} service={service} />)}</div>}</div>}
  </PageShell>;
}

function ServiceCard({ service }: { service: any }) { return <Card className="h-full border-border/60 p-5 transition-shadow hover:shadow-[var(--shadow-soft)]"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg" style={{ fontFamily: "Fraunces, serif" }}>{service.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{service.description || "Service de conciergerie à configurer."}</p></div><Wrench className="h-4 w-4 shrink-0 text-primary" /></div><div className="mt-5 flex flex-wrap gap-2">{service.category && <Badge variant="outline">{service.category}</Badge>}<Badge>{service.price_label ?? (service.price_from != null ? `${service.price_from} ${service.currency ?? "EUR"}` : "Sur demande")}</Badge></div><div className="mt-4 border-t pt-3 text-xs text-muted-foreground">Disponible comme ligne de devis ou prestation opérationnelle.</div></Card> }
