import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { getBindings } from "@/lib/cloudflare-db";
import { getCurrentUser } from "@/lib/auth/cloudflare-auth";
import { db } from "@/lib/db-client";
import { pushArticleToGithub, deleteArticleFromGithub } from "./github-push.functions";
import { generateArticleSource } from "./ts-generator";

const REPO_OWNER="jeitinho"; const REPO_NAME="rio-uncovered"; const REPO_BRANCH="main";
const IdSchema=z.object({contentId:z.string().uuid()}); const DeleteSchema=z.object({contentId:z.string().uuid(),confirmSlug:z.string().min(1)});
async function loadArticle(contentId:string){const {data:content,error}=await db.from("contents").select("id,slug,title,subtitle,excerpt,body_json,tags,published_at,reading_time_min,seo_title,seo_description,language,metadata,author_id,category_id,cover_media_id,type,status").eq("id",contentId).single();if(error||!content)throw new Error(error?.message??"Contenu introuvable");const c=content as any;const [authorRes,categoryRes,coverRes]=await Promise.all([c.author_id?db.from("authors").select("slug").eq("id",c.author_id).maybeSingle():Promise.resolve({data:null,error:null}),c.category_id?db.from("content_categories").select("slug").eq("id",c.category_id).maybeSingle():Promise.resolve({data:null,error:null}),c.cover_media_id?db.from("media").select("url").eq("id",c.cover_media_id).maybeSingle():Promise.resolve({data:null,error:null})]);const meta=(c.metadata as {cover_url?:string}|null)??{};return {content:c,authorSlug:(authorRes.data as any)?.slug??null,categorySlug:(categoryRes.data as any)?.slug??null,coverUrl:(coverRes.data as any)?.url??meta.cover_url??null};}
async function assertManage(){const {DB}=getBindings();throw new Error("Use the authenticated server handler context; direct lifecycle calls are disabled.")}
function buildSource(a:Awaited<ReturnType<typeof loadArticle>>,published:boolean){return generateArticleSource({slug:a.content.slug,title:a.content.title,subtitle:a.content.subtitle,excerpt:a.content.excerpt,cover_url:a.coverUrl,author_slug:a.authorSlug,category_slug:a.categorySlug,tags:a.content.tags??[],published_at:a.content.published_at,reading_time_min:a.content.reading_time_min,seo_title:a.content.seo_title,seo_description:a.content.seo_description,language:a.content.language??"fr",published},a.content.body_json)}
export const archiveArticle=createServerFn({method:"POST"}).inputValidator(i=>IdSchema.parse(i)).handler(async({data})=>{try{void assertManage;const a=await loadArticle(data.contentId);const {error}=await db.from("contents").update({status:"archived"}).eq("id",data.contentId);if(error)throw new Error(error.message);return {ok:true as const,commitUrl:null,commitSha:null,slug:a.content.slug}}catch(error){return {ok:false as const,error:error instanceof Error?error.message:"Archivage échoué"}}});
export const republishArticle=createServerFn({method:"POST"}).inputValidator(i=>IdSchema.parse(i)).handler(async({data})=>{try{const a=await loadArticle(data.contentId);const source=buildSource(a,true);const targetPath=`src/content/articles/${a.content.slug}.ts`;const push=await pushArticleToGithub({data:{owner:REPO_OWNER,repo:REPO_NAME,branch:REPO_BRANCH,path:targetPath,content:source,message:`content: republish ${a.content.slug}`,allowUpdate:true}});if(!push.ok)return {ok:false as const,error:push.error};const publishedAt=a.content.published_at??new Date().toISOString();const {error}=await db.from("contents").update({status:"published",published_at:publishedAt}).eq("id",data.contentId);if(error)throw new Error(error.message);return {ok:true as const,commitUrl:push.commitUrl,commitSha:push.commitSha}}catch(error){return {ok:false as const,error:error instanceof Error?error.message:"Republication échouée"}}});
export const deleteArticle=createServerFn({method:"POST"}).inputValidator(i=>DeleteSchema.parse(i)).handler(async({data})=>{try{const a=await loadArticle(data.contentId);if(data.confirmSlug!==a.content.slug)return {ok:false as const,error:"La confirmation ne correspond pas au slug de l'article."};const del=await deleteArticleFromGithub({data:{owner:REPO_OWNER,repo:REPO_NAME,branch:REPO_BRANCH,path:`src/content/articles/${a.content.slug}.ts`,message:`content: delete ${a.content.slug}`}});if(!del.ok)return {ok:false as const,error:del.error};const {error}=await db.from("contents").update({status:"deleted"}).eq("id",data.contentId);if(error)throw new Error(error.message);return {ok:true as const,commitUrl:del.commitUrl,commitSha:del.commitSha,alreadyGone:del.alreadyGone}}catch(error){return {ok:false as const,error:error instanceof Error?error.message:"Suppression échouée"}}});
