/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVoyagesRouteImport } from './routes/_authenticated/voyages'
import { Route as AuthenticatedPartenairesRouteImport } from './routes/_authenticated/partenaires'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedMediathequeRouteImport } from './routes/_authenticated/mediatheque'
import { Route as AuthenticatedExperiencesRouteImport } from './routes/_authenticated/experiences'
import { Route as AuthenticatedDevisRouteImport } from './routes/_authenticated/devis'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedContenusRouteImport } from './routes/_authenticated/contenus'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCalendrierRouteImport } from './routes/_authenticated/calendrier'
import { Route as AuthenticatedBlogRouteImport } from './routes/_authenticated/blog'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedParametresUtilisateursRouteImport } from './routes/_authenticated/parametres.utilisateurs'
import { Route as AuthenticatedExperiencesNewRouteImport } from './routes/_authenticated/experiences.new'
import { Route as AuthenticatedExperiencesIdRouteImport } from './routes/_authenticated/experiences.$id'
import { Route as AuthenticatedBlogNewRouteImport } from './routes/_authenticated/blog.new'
import { Route as AuthenticatedBlogIdRouteImport } from './routes/_authenticated/blog.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoyagesRoute = AuthenticatedVoyagesRouteImport.update({
  id: '/voyages',
  path: '/voyages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartenairesRoute =
  AuthenticatedPartenairesRouteImport.update({
    id: '/partenaires',
    path: '/partenaires',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediathequeRoute =
  AuthenticatedMediathequeRouteImport.update({
    id: '/mediatheque',
    path: '/mediatheque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExperiencesRoute =
  AuthenticatedExperiencesRouteImport.update({
    id: '/experiences',
    path: '/experiences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevisRoute = AuthenticatedDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContenusRoute = AuthenticatedContenusRouteImport.update({
  id: '/contenus',
  path: '/contenus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendrierRoute = AuthenticatedCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlogRoute = AuthenticatedBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresUtilisateursRoute =
  AuthenticatedParametresUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedParametresRoute,
  } as any)
const AuthenticatedExperiencesNewRoute =
  AuthenticatedExperiencesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedExperiencesRoute,
  } as any)
const AuthenticatedExperiencesIdRoute =
  AuthenticatedExperiencesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedExperiencesRoute,
  } as any)
const AuthenticatedBlogNewRoute = AuthenticatedBlogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedBlogRoute,
} as any)
const AuthenticatedBlogIdRoute = AuthenticatedBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/blog': typeof AuthenticatedBlogRouteWithChildren
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/contenus': typeof AuthenticatedContenusRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devis': typeof AuthenticatedDevisRoute
  '/experiences': typeof AuthenticatedExperiencesRouteWithChildren
  '/mediatheque': typeof AuthenticatedMediathequeRoute
  '/parametres': typeof AuthenticatedParametresRouteWithChildren
  '/partenaires': typeof AuthenticatedPartenairesRoute
  '/voyages': typeof AuthenticatedVoyagesRoute
  '/blog/$id': typeof AuthenticatedBlogIdRoute
  '/blog/new': typeof AuthenticatedBlogNewRoute
  '/experiences/$id': typeof AuthenticatedExperiencesIdRoute
  '/experiences/new': typeof AuthenticatedExperiencesNewRoute
  '/parametres/utilisateurs': typeof AuthenticatedParametresUtilisateursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/blog': typeof AuthenticatedBlogRouteWithChildren
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/contenus': typeof AuthenticatedContenusRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devis': typeof AuthenticatedDevisRoute
  '/experiences': typeof AuthenticatedExperiencesRouteWithChildren
  '/mediatheque': typeof AuthenticatedMediathequeRoute
  '/parametres': typeof AuthenticatedParametresRouteWithChildren
  '/partenaires': typeof AuthenticatedPartenairesRoute
  '/voyages': typeof AuthenticatedVoyagesRoute
  '/blog/$id': typeof AuthenticatedBlogIdRoute
  '/blog/new': typeof AuthenticatedBlogNewRoute
  '/experiences/$id': typeof AuthenticatedExperiencesIdRoute
  '/experiences/new': typeof AuthenticatedExperiencesNewRoute
  '/parametres/utilisateurs': typeof AuthenticatedParametresUtilisateursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/blog': typeof AuthenticatedBlogRouteWithChildren
  '/_authenticated/calendrier': typeof AuthenticatedCalendrierRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/contenus': typeof AuthenticatedContenusRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devis': typeof AuthenticatedDevisRoute
  '/_authenticated/experiences': typeof AuthenticatedExperiencesRouteWithChildren
  '/_authenticated/mediatheque': typeof AuthenticatedMediathequeRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRouteWithChildren
  '/_authenticated/partenaires': typeof AuthenticatedPartenairesRoute
  '/_authenticated/voyages': typeof AuthenticatedVoyagesRoute
  '/_authenticated/blog/$id': typeof AuthenticatedBlogIdRoute
  '/_authenticated/blog/new': typeof AuthenticatedBlogNewRoute
  '/_authenticated/experiences/$id': typeof AuthenticatedExperiencesIdRoute
  '/_authenticated/experiences/new': typeof AuthenticatedExperiencesNewRoute
  '/_authenticated/parametres/utilisateurs': typeof AuthenticatedParametresUtilisateursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/analytics'
    | '/blog'
    | '/calendrier'
    | '/clients'
    | '/contenus'
    | '/crm'
    | '/dashboard'
    | '/devis'
    | '/experiences'
    | '/mediatheque'
    | '/parametres'
    | '/partenaires'
    | '/voyages'
    | '/blog/$id'
    | '/blog/new'
    | '/experiences/$id'
    | '/experiences/new'
    | '/parametres/utilisateurs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/analytics'
    | '/blog'
    | '/calendrier'
    | '/clients'
    | '/contenus'
    | '/crm'
    | '/dashboard'
    | '/devis'
    | '/experiences'
    | '/mediatheque'
    | '/parametres'
    | '/partenaires'
    | '/voyages'
    | '/blog/$id'
    | '/blog/new'
    | '/experiences/$id'
    | '/experiences/new'
    | '/parametres/utilisateurs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/_authenticated/analytics'
    | '/_authenticated/blog'
    | '/_authenticated/calendrier'
    | '/_authenticated/clients'
    | '/_authenticated/contenus'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/devis'
    | '/_authenticated/experiences'
    | '/_authenticated/mediatheque'
    | '/_authenticated/parametres'
    | '/_authenticated/partenaires'
    | '/_authenticated/voyages'
    | '/_authenticated/blog/$id'
    | '/_authenticated/blog/new'
    | '/_authenticated/experiences/$id'
    | '/_authenticated/experiences/new'
    | '/_authenticated/parametres/utilisateurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voyages': {
      id: '/_authenticated/voyages'
      path: '/voyages'
      fullPath: '/voyages'
      preLoaderRoute: typeof AuthenticatedVoyagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partenaires': {
      id: '/_authenticated/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof AuthenticatedPartenairesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mediatheque': {
      id: '/_authenticated/mediatheque'
      path: '/mediatheque'
      fullPath: '/mediatheque'
      preLoaderRoute: typeof AuthenticatedMediathequeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiences': {
      id: '/_authenticated/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof AuthenticatedExperiencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devis': {
      id: '/_authenticated/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof AuthenticatedDevisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contenus': {
      id: '/_authenticated/contenus'
      path: '/contenus'
      fullPath: '/contenus'
      preLoaderRoute: typeof AuthenticatedContenusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendrier': {
      id: '/_authenticated/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof AuthenticatedCalendrierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blog': {
      id: '/_authenticated/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AuthenticatedBlogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres/utilisateurs': {
      id: '/_authenticated/parametres/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/parametres/utilisateurs'
      preLoaderRoute: typeof AuthenticatedParametresUtilisateursRouteImport
      parentRoute: typeof AuthenticatedParametresRoute
    }
    '/_authenticated/experiences/new': {
      id: '/_authenticated/experiences/new'
      path: '/new'
      fullPath: '/experiences/new'
      preLoaderRoute: typeof AuthenticatedExperiencesNewRouteImport
      parentRoute: typeof AuthenticatedExperiencesRoute
    }
    '/_authenticated/experiences/$id': {
      id: '/_authenticated/experiences/$id'
      path: '/$id'
      fullPath: '/experiences/$id'
      preLoaderRoute: typeof AuthenticatedExperiencesIdRouteImport
      parentRoute: typeof AuthenticatedExperiencesRoute
    }
    '/_authenticated/blog/new': {
      id: '/_authenticated/blog/new'
      path: '/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof AuthenticatedBlogNewRouteImport
      parentRoute: typeof AuthenticatedBlogRoute
    }
    '/_authenticated/blog/$id': {
      id: '/_authenticated/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof AuthenticatedBlogIdRouteImport
      parentRoute: typeof AuthenticatedBlogRoute
    }
  }
}

interface AuthenticatedBlogRouteChildren {
  AuthenticatedBlogIdRoute: typeof AuthenticatedBlogIdRoute
  AuthenticatedBlogNewRoute: typeof AuthenticatedBlogNewRoute
}

const AuthenticatedBlogRouteChildren: AuthenticatedBlogRouteChildren = {
  AuthenticatedBlogIdRoute: AuthenticatedBlogIdRoute,
  AuthenticatedBlogNewRoute: AuthenticatedBlogNewRoute,
}

const AuthenticatedBlogRouteWithChildren =
  AuthenticatedBlogRoute._addFileChildren(AuthenticatedBlogRouteChildren)

interface AuthenticatedExperiencesRouteChildren {
  AuthenticatedExperiencesIdRoute: typeof AuthenticatedExperiencesIdRoute
  AuthenticatedExperiencesNewRoute: typeof AuthenticatedExperiencesNewRoute
}

const AuthenticatedExperiencesRouteChildren: AuthenticatedExperiencesRouteChildren =
  {
    AuthenticatedExperiencesIdRoute: AuthenticatedExperiencesIdRoute,
    AuthenticatedExperiencesNewRoute: AuthenticatedExperiencesNewRoute,
  }

const AuthenticatedExperiencesRouteWithChildren =
  AuthenticatedExperiencesRoute._addFileChildren(
    AuthenticatedExperiencesRouteChildren,
  )

interface AuthenticatedParametresRouteChildren {
  AuthenticatedParametresUtilisateursRoute: typeof AuthenticatedParametresUtilisateursRoute
}

const AuthenticatedParametresRouteChildren: AuthenticatedParametresRouteChildren =
  {
    AuthenticatedParametresUtilisateursRoute:
      AuthenticatedParametresUtilisateursRoute,
  }

const AuthenticatedParametresRouteWithChildren =
  AuthenticatedParametresRoute._addFileChildren(
    AuthenticatedParametresRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBlogRoute: typeof AuthenticatedBlogRouteWithChildren
  AuthenticatedCalendrierRoute: typeof AuthenticatedCalendrierRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedContenusRoute: typeof AuthenticatedContenusRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevisRoute: typeof AuthenticatedDevisRoute
  AuthenticatedExperiencesRoute: typeof AuthenticatedExperiencesRouteWithChildren
  AuthenticatedMediathequeRoute: typeof AuthenticatedMediathequeRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRouteWithChildren
  AuthenticatedPartenairesRoute: typeof AuthenticatedPartenairesRoute
  AuthenticatedVoyagesRoute: typeof AuthenticatedVoyagesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBlogRoute: AuthenticatedBlogRouteWithChildren,
  AuthenticatedCalendrierRoute: AuthenticatedCalendrierRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedContenusRoute: AuthenticatedContenusRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevisRoute: AuthenticatedDevisRoute,
  AuthenticatedExperiencesRoute: AuthenticatedExperiencesRouteWithChildren,
  AuthenticatedMediathequeRoute: AuthenticatedMediathequeRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRouteWithChildren,
  AuthenticatedPartenairesRoute: AuthenticatedPartenairesRoute,
  AuthenticatedVoyagesRoute: AuthenticatedVoyagesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
