/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedBilletterieRouteImport } from './routes/_authenticated/billetterie'
import { Route as AuthenticatedBlogRouteImport } from './routes/_authenticated/blog'
import { Route as AuthenticatedCalendrierRouteImport } from './routes/_authenticated/calendrier'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedContenusRouteImport } from './routes/_authenticated/contenus'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDevisRouteImport } from './routes/_authenticated/devis'
import { Route as AuthenticatedExperiencesRouteImport } from './routes/_authenticated/experiences'
import { Route as AuthenticatedMediathequeRouteImport } from './routes/_authenticated/mediatheque'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedPartenairesRouteImport } from './routes/_authenticated/partenaires'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedVoyagesRouteImport } from './routes/_authenticated/voyages'
import { Route as AuthenticatedBilletterieIdRouteImport } from './routes/_authenticated/billetterie.$id'
import { Route as AuthenticatedBilletterieNewRouteImport } from './routes/_authenticated/billetterie.new'
import { Route as AuthenticatedBlogIdRouteImport } from './routes/_authenticated/blog.$id'
import { Route as AuthenticatedBlogNewRouteImport } from './routes/_authenticated/blog.new'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedDevisIdRouteImport } from './routes/_authenticated/devis.$id'
import { Route as AuthenticatedDevisNewRouteImport } from './routes/_authenticated/devis.new'
import { Route as AuthenticatedExperiencesIdRouteImport } from './routes/_authenticated/experiences.$id'
import { Route as AuthenticatedExperiencesNewRouteImport } from './routes/_authenticated/experiences.new'
import { Route as AuthenticatedParametresUtilisateursRouteImport } from './routes/_authenticated/parametres.utilisateurs'
import { Route as AuthenticatedServicesIdRouteImport } from './routes/_authenticated/services.$id'
import { Route as AuthenticatedServicesNewRouteImport } from './routes/_authenticated/services.new'
import { Route as AuthenticatedVoyagesIdRouteImport } from './routes/_authenticated/voyages.$id'
import { Route as AuthenticatedVoyagesNewRouteImport } from './routes/_authenticated/voyages.new'
import { Route as ApiAuthDiagnosticsRouteImport } from './routes/api/auth/diagnostics'
import { Route as ApiAuthDiagnosticsLoginRouteImport } from './routes/api/auth/diagnostics-login'
import { Route as ApiAuthDiagnosticsLogoRouteImport } from './routes/api/auth/diagnostics-logo'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthRequestResetRouteImport } from './routes/api/auth/request-reset'
import { Route as ApiAuthResetPasswordRouteImport } from './routes/api/auth/reset-password'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiDbQueryRouteImport } from './routes/api/db/query'
import { Route as ApiDbRpcRouteImport } from './routes/api/db/rpc'
import { Route as ApiInternalCatalogRouteImport } from './routes/api/internal/catalog'
import { Route as ApiInternalHealthRouteImport } from './routes/api/internal/health'
import { Route as ApiStorageFileRouteImport } from './routes/api/storage/file'
import { Route as ApiStorageSignedUrlRouteImport } from './routes/api/storage/signed-url'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'
import { Route as ApiContentContentIdWorkflowRouteImport } from './routes/api/content/$contentId/workflow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBilletterieRoute =
  AuthenticatedBilletterieRouteImport.update({
    id: '/billetterie',
    path: '/billetterie',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBlogRoute = AuthenticatedBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendrierRoute = AuthenticatedCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContenusRoute = AuthenticatedContenusRouteImport.update({
  id: '/contenus',
  path: '/contenus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevisRoute = AuthenticatedDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExperiencesRoute =
  AuthenticatedExperiencesRouteImport.update({
    id: '/experiences',
    path: '/experiences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediathequeRoute =
  AuthenticatedMediathequeRouteImport.update({
    id: '/mediatheque',
    path: '/mediatheque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartenairesRoute =
  AuthenticatedPartenairesRouteImport.update({
    id: '/partenaires',
    path: '/partenaires',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVoyagesRoute = AuthenticatedVoyagesRouteImport.update({
  id: '/voyages',
  path: '/voyages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBilletterieIdRoute =
  AuthenticatedBilletterieIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedBilletterieRoute,
  } as any)
const AuthenticatedBilletterieNewRoute =
  AuthenticatedBilletterieNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedBilletterieRoute,
  } as any)
const AuthenticatedBlogIdRoute = AuthenticatedBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBlogRoute,
} as any)
const AuthenticatedBlogNewRoute = AuthenticatedBlogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedBlogRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedDevisIdRoute = AuthenticatedDevisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDevisRoute,
} as any)
const AuthenticatedDevisNewRoute = AuthenticatedDevisNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedDevisRoute,
} as any)
const AuthenticatedExperiencesIdRoute =
  AuthenticatedExperiencesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedExperiencesRoute,
  } as any)
const AuthenticatedExperiencesNewRoute =
  AuthenticatedExperiencesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedExperiencesRoute,
  } as any)
const AuthenticatedParametresUtilisateursRoute =
  AuthenticatedParametresUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedParametresRoute,
  } as any)
const AuthenticatedServicesIdRoute = AuthenticatedServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedServicesRoute,
} as any)
const AuthenticatedServicesNewRoute =
  AuthenticatedServicesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedServicesRoute,
  } as any)
const AuthenticatedVoyagesIdRoute = AuthenticatedVoyagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedVoyagesRoute,
} as any)
const AuthenticatedVoyagesNewRoute = AuthenticatedVoyagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedVoyagesRoute,
} as any)
const ApiAuthDiagnosticsRoute = ApiAuthDiagnosticsRouteImport.update({
  id: '/api/auth/diagnostics',
  path: '/api/auth/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiagnosticsLoginRoute = ApiAuthDiagnosticsLoginRouteImport.update({
  id: '/api/auth/diagnostics-login',
  path: '/api/auth/diagnostics-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiagnosticsLogoRoute = ApiAuthDiagnosticsLogoRouteImport.update({
  id: '/api/auth/diagnostics-logo',
  path: '/api/auth/diagnostics-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRequestResetRoute = ApiAuthRequestResetRouteImport.update({
  id: '/api/auth/request-reset',
  path: '/api/auth/request-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/api/auth/reset-password',
  path: '/api/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbQueryRoute = ApiDbQueryRouteImport.update({
  id: '/api/db/query',
  path: '/api/db/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbRpcRoute = ApiDbRpcRouteImport.update({
  id: '/api/db/rpc',
  path: '/api/db/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalCatalogRoute = ApiInternalCatalogRouteImport.update({
  id: '/api/internal/catalog',
  path: '/api/internal/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalHealthRoute = ApiInternalHealthRouteImport.update({
  id: '/api/internal/health',
  path: '/api/internal/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFileRoute = ApiStorageFileRouteImport.update({
  id: '/api/storage/file',
  path: '/api/storage/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageSignedUrlRoute = ApiStorageSignedUrlRouteImport.update({
  id: '/api/storage/signed-url',
  path: '/api/storage/signed-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentContentIdWorkflowRoute =
  ApiContentContentIdWorkflowRouteImport.update({
    id: '/api/content/$contentId/workflow',
    path: '/api/content/$contentId/workflow',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billetterie': typeof AuthenticatedBilletterieRouteWithChildren
  '/blog': typeof AuthenticatedBlogRouteWithChildren
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/contenus': typeof AuthenticatedContenusRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devis': typeof AuthenticatedDevisRouteWithChildren
  '/experiences': typeof AuthenticatedExperiencesRouteWithChildren
  '/mediatheque': typeof AuthenticatedMediathequeRoute
  '/parametres': typeof AuthenticatedParametresRouteWithChildren
  '/partenaires': typeof AuthenticatedPartenairesRoute
  '/services': typeof AuthenticatedServicesRouteWithChildren
  '/voyages': typeof AuthenticatedVoyagesRouteWithChildren
  '/billetterie/$id': typeof AuthenticatedBilletterieIdRoute
  '/billetterie/new': typeof AuthenticatedBilletterieNewRoute
  '/blog/$id': typeof AuthenticatedBlogIdRoute
  '/blog/new': typeof AuthenticatedBlogNewRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/devis/$id': typeof AuthenticatedDevisIdRoute
  '/devis/new': typeof AuthenticatedDevisNewRoute
  '/experiences/$id': typeof AuthenticatedExperiencesIdRoute
  '/experiences/new': typeof AuthenticatedExperiencesNewRoute
  '/parametres/utilisateurs': typeof AuthenticatedParametresUtilisateursRoute
  '/services/$id': typeof AuthenticatedServicesIdRoute
  '/services/new': typeof AuthenticatedServicesNewRoute
  '/voyages/$id': typeof AuthenticatedVoyagesIdRoute
  '/voyages/new': typeof AuthenticatedVoyagesNewRoute
  '/api/auth/diagnostics': typeof ApiAuthDiagnosticsRoute
  '/api/auth/diagnostics-login': typeof ApiAuthDiagnosticsLoginRoute
  '/api/auth/diagnostics-logo': typeof ApiAuthDiagnosticsLogoRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/request-reset': typeof ApiAuthRequestResetRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/db/query': typeof ApiDbQueryRoute
  '/api/db/rpc': typeof ApiDbRpcRoute
  '/api/internal/catalog': typeof ApiInternalCatalogRoute
  '/api/internal/health': typeof ApiInternalHealthRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/signed-url': typeof ApiStorageSignedUrlRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/content/$contentId/workflow': typeof ApiContentContentIdWorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billetterie': typeof AuthenticatedBilletterieRouteWithChildren
  '/blog': typeof AuthenticatedBlogRouteWithChildren
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/contenus': typeof AuthenticatedContenusRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devis': typeof AuthenticatedDevisRouteWithChildren
  '/experiences': typeof AuthenticatedExperiencesRouteWithChildren
  '/mediatheque': typeof AuthenticatedMediathequeRoute
  '/parametres': typeof AuthenticatedParametresRouteWithChildren
  '/partenaires': typeof AuthenticatedPartenairesRoute
  '/services': typeof AuthenticatedServicesRouteWithChildren
  '/voyages': typeof AuthenticatedVoyagesRouteWithChildren
  '/billetterie/$id': typeof AuthenticatedBilletterieIdRoute
  '/billetterie/new': typeof AuthenticatedBilletterieNewRoute
  '/blog/$id': typeof AuthenticatedBlogIdRoute
  '/blog/new': typeof AuthenticatedBlogNewRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/devis/$id': typeof AuthenticatedDevisIdRoute
  '/devis/new': typeof AuthenticatedDevisNewRoute
  '/experiences/$id': typeof AuthenticatedExperiencesIdRoute
  '/experiences/new': typeof AuthenticatedExperiencesNewRoute
  '/parametres/utilisateurs': typeof AuthenticatedParametresUtilisateursRoute
  '/services/$id': typeof AuthenticatedServicesIdRoute
  '/services/new': typeof AuthenticatedServicesNewRoute
  '/voyages/$id': typeof AuthenticatedVoyagesIdRoute
  '/voyages/new': typeof AuthenticatedVoyagesNewRoute
  '/api/auth/diagnostics': typeof ApiAuthDiagnosticsRoute
  '/api/auth/diagnostics-login': typeof ApiAuthDiagnosticsLoginRoute
  '/api/auth/diagnostics-logo': typeof ApiAuthDiagnosticsLogoRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/request-reset': typeof ApiAuthRequestResetRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/db/query': typeof ApiDbQueryRoute
  '/api/db/rpc': typeof ApiDbRpcRoute
  '/api/internal/catalog': typeof ApiInternalCatalogRoute
  '/api/internal/health': typeof ApiInternalHealthRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/signed-url': typeof ApiStorageSignedUrlRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/content/$contentId/workflow': typeof ApiContentContentIdWorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/billetterie': typeof AuthenticatedBilletterieRouteWithChildren
  '/_authenticated/blog': typeof AuthenticatedBlogRouteWithChildren
  '/_authenticated/calendrier': typeof AuthenticatedCalendrierRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/contenus': typeof AuthenticatedContenusRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devis': typeof AuthenticatedDevisRouteWithChildren
  '/_authenticated/experiences': typeof AuthenticatedExperiencesRouteWithChildren
  '/_authenticated/mediatheque': typeof AuthenticatedMediathequeRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRouteWithChildren
  '/_authenticated/partenaires': typeof AuthenticatedPartenairesRoute
  '/_authenticated/services': typeof AuthenticatedServicesRouteWithChildren
  '/_authenticated/voyages': typeof AuthenticatedVoyagesRouteWithChildren
  '/_authenticated/billetterie/$id': typeof AuthenticatedBilletterieIdRoute
  '/_authenticated/billetterie/new': typeof AuthenticatedBilletterieNewRoute
  '/_authenticated/blog/$id': typeof AuthenticatedBlogIdRoute
  '/_authenticated/blog/new': typeof AuthenticatedBlogNewRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/devis/$id': typeof AuthenticatedDevisIdRoute
  '/_authenticated/devis/new': typeof AuthenticatedDevisNewRoute
  '/_authenticated/experiences/$id': typeof AuthenticatedExperiencesIdRoute
  '/_authenticated/experiences/new': typeof AuthenticatedExperiencesNewRoute
  '/_authenticated/parametres/utilisateurs': typeof AuthenticatedParametresUtilisateursRoute
  '/_authenticated/services/$id': typeof AuthenticatedServicesIdRoute
  '/_authenticated/services/new': typeof AuthenticatedServicesNewRoute
  '/_authenticated/voyages/$id': typeof AuthenticatedVoyagesIdRoute
  '/_authenticated/voyages/new': typeof AuthenticatedVoyagesNewRoute
  '/api/auth/diagnostics': typeof ApiAuthDiagnosticsRoute
  '/api/auth/diagnostics-login': typeof ApiAuthDiagnosticsLoginRoute
  '/api/auth/diagnostics-logo': typeof ApiAuthDiagnosticsLogoRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/request-reset': typeof ApiAuthRequestResetRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/db/query': typeof ApiDbQueryRoute
  '/api/db/rpc': typeof ApiDbRpcRoute
  '/api/internal/catalog': typeof ApiInternalCatalogRoute
  '/api/internal/health': typeof ApiInternalHealthRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/signed-url': typeof ApiStorageSignedUrlRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/content/$contentId/workflow': typeof ApiContentContentIdWorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/analytics'
    | '/billetterie'
    | '/blog'
    | '/calendrier'
    | '/clients'
    | '/contenus'
    | '/crm'
    | '/dashboard'
    | '/devis'
    | '/experiences'
    | '/mediatheque'
    | '/parametres'
    | '/partenaires'
    | '/services'
    | '/voyages'
    | '/billetterie/$id'
    | '/billetterie/new'
    | '/blog/$id'
    | '/blog/new'
    | '/clients/$id'
    | '/devis/$id'
    | '/devis/new'
    | '/experiences/$id'
    | '/experiences/new'
    | '/parametres/utilisateurs'
    | '/services/$id'
    | '/services/new'
    | '/voyages/$id'
    | '/voyages/new'
    | '/api/auth/diagnostics'
    | '/api/auth/diagnostics-login'
    | '/api/auth/diagnostics-logo'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/request-reset'
    | '/api/auth/reset-password'
    | '/api/auth/signup'
    | '/api/db/query'
    | '/api/db/rpc'
    | '/api/internal/catalog'
    | '/api/internal/health'
    | '/api/storage/file'
    | '/api/storage/signed-url'
    | '/api/storage/upload'
    | '/api/content/$contentId/workflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/analytics'
    | '/billetterie'
    | '/blog'
    | '/calendrier'
    | '/clients'
    | '/contenus'
    | '/crm'
    | '/dashboard'
    | '/devis'
    | '/experiences'
    | '/mediatheque'
    | '/parametres'
    | '/partenaires'
    | '/services'
    | '/voyages'
    | '/billetterie/$id'
    | '/billetterie/new'
    | '/blog/$id'
    | '/blog/new'
    | '/clients/$id'
    | '/devis/$id'
    | '/devis/new'
    | '/experiences/$id'
    | '/experiences/new'
    | '/parametres/utilisateurs'
    | '/services/$id'
    | '/services/new'
    | '/voyages/$id'
    | '/voyages/new'
    | '/api/auth/diagnostics'
    | '/api/auth/diagnostics-login'
    | '/api/auth/diagnostics-logo'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/request-reset'
    | '/api/auth/reset-password'
    | '/api/auth/signup'
    | '/api/db/query'
    | '/api/db/rpc'
    | '/api/internal/catalog'
    | '/api/internal/health'
    | '/api/storage/file'
    | '/api/storage/signed-url'
    | '/api/storage/upload'
    | '/api/content/$contentId/workflow'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/_authenticated/analytics'
    | '/_authenticated/billetterie'
    | '/_authenticated/blog'
    | '/_authenticated/calendrier'
    | '/_authenticated/clients'
    | '/_authenticated/contenus'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/devis'
    | '/_authenticated/experiences'
    | '/_authenticated/mediatheque'
    | '/_authenticated/parametres'
    | '/_authenticated/partenaires'
    | '/_authenticated/services'
    | '/_authenticated/voyages'
    | '/_authenticated/billetterie/$id'
    | '/_authenticated/billetterie/new'
    | '/_authenticated/blog/$id'
    | '/_authenticated/blog/new'
    | '/_authenticated/clients/$id'
    | '/_authenticated/devis/$id'
    | '/_authenticated/devis/new'
    | '/_authenticated/experiences/$id'
    | '/_authenticated/experiences/new'
    | '/_authenticated/parametres/utilisateurs'
    | '/_authenticated/services/$id'
    | '/_authenticated/services/new'
    | '/_authenticated/voyages/$id'
    | '/_authenticated/voyages/new'
    | '/api/auth/diagnostics'
    | '/api/auth/diagnostics-login'
    | '/api/auth/diagnostics-logo'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/request-reset'
    | '/api/auth/reset-password'
    | '/api/auth/signup'
    | '/api/db/query'
    | '/api/db/rpc'
    | '/api/internal/catalog'
    | '/api/internal/health'
    | '/api/storage/file'
    | '/api/storage/signed-url'
    | '/api/storage/upload'
    | '/api/content/$contentId/workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  ApiAuthDiagnosticsRoute: typeof ApiAuthDiagnosticsRoute
  ApiAuthDiagnosticsLoginRoute: typeof ApiAuthDiagnosticsLoginRoute
  ApiAuthDiagnosticsLogoRoute: typeof ApiAuthDiagnosticsLogoRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRequestResetRoute: typeof ApiAuthRequestResetRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiDbQueryRoute: typeof ApiDbQueryRoute
  ApiDbRpcRoute: typeof ApiDbRpcRoute
  ApiInternalCatalogRoute: typeof ApiInternalCatalogRoute
  ApiInternalHealthRoute: typeof ApiInternalHealthRoute
  ApiStorageFileRoute: typeof ApiStorageFileRoute
  ApiStorageSignedUrlRoute: typeof ApiStorageSignedUrlRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
  ApiContentContentIdWorkflowRoute: typeof ApiContentContentIdWorkflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billetterie': {
      id: '/_authenticated/billetterie'
      path: '/billetterie'
      fullPath: '/billetterie'
      preLoaderRoute: typeof AuthenticatedBilletterieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blog': {
      id: '/_authenticated/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AuthenticatedBlogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendrier': {
      id: '/_authenticated/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof AuthenticatedCalendrierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contenus': {
      id: '/_authenticated/contenus'
      path: '/contenus'
      fullPath: '/contenus'
      preLoaderRoute: typeof AuthenticatedContenusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devis': {
      id: '/_authenticated/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof AuthenticatedDevisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiences': {
      id: '/_authenticated/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof AuthenticatedExperiencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mediatheque': {
      id: '/_authenticated/mediatheque'
      path: '/mediatheque'
      fullPath: '/mediatheque'
      preLoaderRoute: typeof AuthenticatedMediathequeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partenaires': {
      id: '/_authenticated/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof AuthenticatedPartenairesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voyages': {
      id: '/_authenticated/voyages'
      path: '/voyages'
      fullPath: '/voyages'
      preLoaderRoute: typeof AuthenticatedVoyagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billetterie/$id': {
      id: '/_authenticated/billetterie/$id'
      path: '/$id'
      fullPath: '/billetterie/$id'
      preLoaderRoute: typeof AuthenticatedBilletterieIdRouteImport
      parentRoute: typeof AuthenticatedBilletterieRoute
    }
    '/_authenticated/billetterie/new': {
      id: '/_authenticated/billetterie/new'
      path: '/new'
      fullPath: '/billetterie/new'
      preLoaderRoute: typeof AuthenticatedBilletterieNewRouteImport
      parentRoute: typeof AuthenticatedBilletterieRoute
    }
    '/_authenticated/blog/$id': {
      id: '/_authenticated/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof AuthenticatedBlogIdRouteImport
      parentRoute: typeof AuthenticatedBlogRoute
    }
    '/_authenticated/blog/new': {
      id: '/_authenticated/blog/new'
      path: '/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof AuthenticatedBlogNewRouteImport
      parentRoute: typeof AuthenticatedBlogRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/devis/$id': {
      id: '/_authenticated/devis/$id'
      path: '/$id'
      fullPath: '/devis/$id'
      preLoaderRoute: typeof AuthenticatedDevisIdRouteImport
      parentRoute: typeof AuthenticatedDevisRoute
    }
    '/_authenticated/devis/new': {
      id: '/_authenticated/devis/new'
      path: '/new'
      fullPath: '/devis/new'
      preLoaderRoute: typeof AuthenticatedDevisNewRouteImport
      parentRoute: typeof AuthenticatedDevisRoute
    }
    '/_authenticated/experiences/$id': {
      id: '/_authenticated/experiences/$id'
      path: '/$id'
      fullPath: '/experiences/$id'
      preLoaderRoute: typeof AuthenticatedExperiencesIdRouteImport
      parentRoute: typeof AuthenticatedExperiencesRoute
    }
    '/_authenticated/experiences/new': {
      id: '/_authenticated/experiences/new'
      path: '/new'
      fullPath: '/experiences/new'
      preLoaderRoute: typeof AuthenticatedExperiencesNewRouteImport
      parentRoute: typeof AuthenticatedExperiencesRoute
    }
    '/_authenticated/parametres/utilisateurs': {
      id: '/_authenticated/parametres/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/parametres/utilisateurs'
      preLoaderRoute: typeof AuthenticatedParametresUtilisateursRouteImport
      parentRoute: typeof AuthenticatedParametresRoute
    }
    '/_authenticated/services/$id': {
      id: '/_authenticated/services/$id'
      path: '/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof AuthenticatedServicesIdRouteImport
      parentRoute: typeof AuthenticatedServicesRoute
    }
    '/_authenticated/services/new': {
      id: '/_authenticated/services/new'
      path: '/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof AuthenticatedServicesNewRouteImport
      parentRoute: typeof AuthenticatedServicesRoute
    }
    '/_authenticated/voyages/$id': {
      id: '/_authenticated/voyages/$id'
      path: '/$id'
      fullPath: '/voyages/$id'
      preLoaderRoute: typeof AuthenticatedVoyagesIdRouteImport
      parentRoute: typeof AuthenticatedVoyagesRoute
    }
    '/_authenticated/voyages/new': {
      id: '/_authenticated/voyages/new'
      path: '/new'
      fullPath: '/voyages/new'
      preLoaderRoute: typeof AuthenticatedVoyagesNewRouteImport
      parentRoute: typeof AuthenticatedVoyagesRoute
    }
    '/api/auth/diagnostics': {
      id: '/api/auth/diagnostics'
      path: '/api/auth/diagnostics'
      fullPath: '/api/auth/diagnostics'
      preLoaderRoute: typeof ApiAuthDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/diagnostics-login': {
      id: '/api/auth/diagnostics-login'
      path: '/api/auth/diagnostics-login'
      fullPath: '/api/auth/diagnostics-login'
      preLoaderRoute: typeof ApiAuthDiagnosticsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/diagnostics-logo': {
      id: '/api/auth/diagnostics-logo'
      path: '/api/auth/diagnostics-logo'
      fullPath: '/api/auth/diagnostics-logo'
      preLoaderRoute: typeof ApiAuthDiagnosticsLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/request-reset': {
      id: '/api/auth/request-reset'
      path: '/api/auth/request-reset'
      fullPath: '/api/auth/request-reset'
      preLoaderRoute: typeof ApiAuthRequestResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/api/auth/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/query': {
      id: '/api/db/query'
      path: '/api/db/query'
      fullPath: '/api/db/query'
      preLoaderRoute: typeof ApiDbQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/rpc': {
      id: '/api/db/rpc'
      path: '/api/db/rpc'
      fullPath: '/api/db/rpc'
      preLoaderRoute: typeof ApiDbRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/catalog': {
      id: '/api/internal/catalog'
      path: '/api/internal/catalog'
      fullPath: '/api/internal/catalog'
      preLoaderRoute: typeof ApiInternalCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/health': {
      id: '/api/internal/health'
      path: '/api/internal/health'
      fullPath: '/api/internal/health'
      preLoaderRoute: typeof ApiInternalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/file': {
      id: '/api/storage/file'
      path: '/api/storage/file'
      fullPath: '/api/storage/file'
      preLoaderRoute: typeof ApiStorageFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/signed-url': {
      id: '/api/storage/signed-url'
      path: '/api/storage/signed-url'
      fullPath: '/api/storage/signed-url'
      preLoaderRoute: typeof ApiStorageSignedUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/$contentId/workflow': {
      id: '/api/content/$contentId/workflow'
      path: '/api/content/$contentId/workflow'
      fullPath: '/api/content/$contentId/workflow'
      preLoaderRoute: typeof ApiContentContentIdWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBilletterieRouteChildren {
  AuthenticatedBilletterieIdRoute: typeof AuthenticatedBilletterieIdRoute
  AuthenticatedBilletterieNewRoute: typeof AuthenticatedBilletterieNewRoute
}

const AuthenticatedBilletterieRouteChildren: AuthenticatedBilletterieRouteChildren =
  {
    AuthenticatedBilletterieIdRoute: AuthenticatedBilletterieIdRoute,
    AuthenticatedBilletterieNewRoute: AuthenticatedBilletterieNewRoute,
  }

const AuthenticatedBilletterieRouteWithChildren =
  AuthenticatedBilletterieRoute._addFileChildren(
    AuthenticatedBilletterieRouteChildren,
  )

interface AuthenticatedBlogRouteChildren {
  AuthenticatedBlogIdRoute: typeof AuthenticatedBlogIdRoute
  AuthenticatedBlogNewRoute: typeof AuthenticatedBlogNewRoute
}

const AuthenticatedBlogRouteChildren: AuthenticatedBlogRouteChildren = {
  AuthenticatedBlogIdRoute: AuthenticatedBlogIdRoute,
  AuthenticatedBlogNewRoute: AuthenticatedBlogNewRoute,
}

const AuthenticatedBlogRouteWithChildren =
  AuthenticatedBlogRoute._addFileChildren(AuthenticatedBlogRouteChildren)

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedDevisRouteChildren {
  AuthenticatedDevisIdRoute: typeof AuthenticatedDevisIdRoute
  AuthenticatedDevisNewRoute: typeof AuthenticatedDevisNewRoute
}

const AuthenticatedDevisRouteChildren: AuthenticatedDevisRouteChildren = {
  AuthenticatedDevisIdRoute: AuthenticatedDevisIdRoute,
  AuthenticatedDevisNewRoute: AuthenticatedDevisNewRoute,
}

const AuthenticatedDevisRouteWithChildren =
  AuthenticatedDevisRoute._addFileChildren(AuthenticatedDevisRouteChildren)

interface AuthenticatedExperiencesRouteChildren {
  AuthenticatedExperiencesIdRoute: typeof AuthenticatedExperiencesIdRoute
  AuthenticatedExperiencesNewRoute: typeof AuthenticatedExperiencesNewRoute
}

const AuthenticatedExperiencesRouteChildren: AuthenticatedExperiencesRouteChildren =
  {
    AuthenticatedExperiencesIdRoute: AuthenticatedExperiencesIdRoute,
    AuthenticatedExperiencesNewRoute: AuthenticatedExperiencesNewRoute,
  }

const AuthenticatedExperiencesRouteWithChildren =
  AuthenticatedExperiencesRoute._addFileChildren(
    AuthenticatedExperiencesRouteChildren,
  )

interface AuthenticatedParametresRouteChildren {
  AuthenticatedParametresUtilisateursRoute: typeof AuthenticatedParametresUtilisateursRoute
}

const AuthenticatedParametresRouteChildren: AuthenticatedParametresRouteChildren =
  {
    AuthenticatedParametresUtilisateursRoute:
      AuthenticatedParametresUtilisateursRoute,
  }

const AuthenticatedParametresRouteWithChildren =
  AuthenticatedParametresRoute._addFileChildren(
    AuthenticatedParametresRouteChildren,
  )

interface AuthenticatedServicesRouteChildren {
  AuthenticatedServicesIdRoute: typeof AuthenticatedServicesIdRoute
  AuthenticatedServicesNewRoute: typeof AuthenticatedServicesNewRoute
}

const AuthenticatedServicesRouteChildren: AuthenticatedServicesRouteChildren = {
  AuthenticatedServicesIdRoute: AuthenticatedServicesIdRoute,
  AuthenticatedServicesNewRoute: AuthenticatedServicesNewRoute,
}

const AuthenticatedServicesRouteWithChildren =
  AuthenticatedServicesRoute._addFileChildren(
    AuthenticatedServicesRouteChildren,
  )

interface AuthenticatedVoyagesRouteChildren {
  AuthenticatedVoyagesIdRoute: typeof AuthenticatedVoyagesIdRoute
  AuthenticatedVoyagesNewRoute: typeof AuthenticatedVoyagesNewRoute
}

const AuthenticatedVoyagesRouteChildren: AuthenticatedVoyagesRouteChildren = {
  AuthenticatedVoyagesIdRoute: AuthenticatedVoyagesIdRoute,
  AuthenticatedVoyagesNewRoute: AuthenticatedVoyagesNewRoute,
}

const AuthenticatedVoyagesRouteWithChildren =
  AuthenticatedVoyagesRoute._addFileChildren(AuthenticatedVoyagesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBilletterieRoute: typeof AuthenticatedBilletterieRouteWithChildren
  AuthenticatedBlogRoute: typeof AuthenticatedBlogRouteWithChildren
  AuthenticatedCalendrierRoute: typeof AuthenticatedCalendrierRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedContenusRoute: typeof AuthenticatedContenusRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevisRoute: typeof AuthenticatedDevisRouteWithChildren
  AuthenticatedExperiencesRoute: typeof AuthenticatedExperiencesRouteWithChildren
  AuthenticatedMediathequeRoute: typeof AuthenticatedMediathequeRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRouteWithChildren
  AuthenticatedPartenairesRoute: typeof AuthenticatedPartenairesRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRouteWithChildren
  AuthenticatedVoyagesRoute: typeof AuthenticatedVoyagesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBilletterieRoute: AuthenticatedBilletterieRouteWithChildren,
  AuthenticatedBlogRoute: AuthenticatedBlogRouteWithChildren,
  AuthenticatedCalendrierRoute: AuthenticatedCalendrierRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedContenusRoute: AuthenticatedContenusRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevisRoute: AuthenticatedDevisRouteWithChildren,
  AuthenticatedExperiencesRoute: AuthenticatedExperiencesRouteWithChildren,
  AuthenticatedMediathequeRoute: AuthenticatedMediathequeRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRouteWithChildren,
  AuthenticatedPartenairesRoute: AuthenticatedPartenairesRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRouteWithChildren,
  AuthenticatedVoyagesRoute: AuthenticatedVoyagesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  ApiAuthDiagnosticsRoute: ApiAuthDiagnosticsRoute,
  ApiAuthDiagnosticsLoginRoute: ApiAuthDiagnosticsLoginRoute,
  ApiAuthDiagnosticsLogoRoute: ApiAuthDiagnosticsLogoRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRequestResetRoute: ApiAuthRequestResetRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiDbQueryRoute: ApiDbQueryRoute,
  ApiDbRpcRoute: ApiDbRpcRoute,
  ApiInternalCatalogRoute: ApiInternalCatalogRoute,
  ApiInternalHealthRoute: ApiInternalHealthRoute,
  ApiStorageFileRoute: ApiStorageFileRoute,
  ApiStorageSignedUrlRoute: ApiStorageSignedUrlRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
  ApiContentContentIdWorkflowRoute: ApiContentContentIdWorkflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
